spring:
  datasource:
    url: jdbc:mysql://localhost:3306/file_compression?useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update